picgur/config/routes.rb
Rails.application.routes.draw do
  root 'pics#index'

  resources :pics

end

picgur/app/models/pic.rb
class Pic < ActiveRecord::Base
end

picgur/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

picgur/app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def index
    @pics = Pic.all
  end

  def show
    @pic = Pic.find(params[:id])
  end

  def new
    @pic = Pic.new
  end

  def create
    @pic = Pic.new(pic_params)
    if @pic.save
      # if the save for the picture was successful, go to index.html.erb
      redirect_to pics_url
    else
      # otherwise render the view associated with the action :new (i.e. new.html.erb)
      render :new
    end
  end

  def edit
    @pic = Pic.find(params[:id])
  end

  def update
    @pic = Pic.find(params[:id])

    if @pic.update_attributes(pic_params)
      redirect_to "/pics/#{@pic.id}"
    else
      render :edit
    end
  end

  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy
    redirect_to pics_url
  end

  private
def pic_params
  params.require(:pic).permit(:art_maker, :art_name, :url)
end

end

picgur/app/helpers/application_helper.rb
module ApplicationHelper
end

picgur/app/helpers/pics_helper.rb
module PicsHelper
end

picgur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picgur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

picgur/app/views/pics/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @pic %>
</p>

<%= form_for @pic do |f| %>
  <p>
    <%= f.label :art_maker %><br>
    <%= f.text_field :art_maker %>
  </p>
  <p>
    <%= f.label :art_name %><br>
    <%= f.text_field :art_name %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

picgur/app/views/pics/index.html.erb
<h1>Pictures (<%= @pics.length %>)</h1>
<%= link_to "New Picture", "/pics/new" %>

<% @pics.each do |item| %>
  <p><%= item.art_maker %>, <%= item.art_name %></p>
  <%= link_to image_tag(item.url), "/pics/#{item.id}" %>
<% end %>

picgur/app/views/pics/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pics_url %>

<%= form_for @pic do |p| %>
  <p>
    <%= p.label :art_maker %><br>
    <%= p.text_field :art_maker %>
  </p>
  <p>
    <%= p.label :art_name %><br>
    <%= p.text_field :art_name %>
  </p>
  <p>
    <%= p.label :url %><br>
    <%= p.text_field :url %>
  </p>
  <p>
    <%= p.submit "Save" %>
  </p>

<% end %>

picgur/app/views/pics/show.html.erb
<%= link_to "Back to Pictures", pics_url %> | <%= link_to "Edit", edit_pic_path(@pic) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>


<p><%= @pic.art_maker %>, <%= @pic.art_name %></p>
<%= image_tag @pic.url %>